-- CREATE TABLE userstable(id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255), email VARCHAR(255));
CREATE TABLE IF NOT EXISTS anothertable(id INT PRIMARY KEY AUTO_INCREMENT, anothername VARCHAR(255));
